services:
  postgres:
    container_name: postgres
    image: postgres:17.5
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 251101
    ports:
      - "5433:5432"